### ISSUE TITLE
🐛 [Bug report]: The page heading is getting overlapped with the navigation bar on the create-play page.

### ISSUE THREAD

**Issue by muzaffar640** [reactplay/react-play#626]
**Describe the bug**
The page heading is getting overlapped with the navigation bar on the create-play page.

**To Reproduce**
1. Up the server locally 
2. . Click on '+ Create'
3. Fill in all details and create a play.
4. On the success page, the heading is overlapping with navigation bar.

**Expected behavior**
The page heading should be clearly visible, there should be little space on the top

**Screenshots**
![Screenshot 2022-10-05 at 9 59 58 AM](https://user-images.githubusercontent.com/55223302/194375121-d0b3f10b-0b67-49b5-bc0a-8bfd509ecb9c.JPG)

**Desktop (please complete the following information):**

OS: iOS
Browser : chrome, firefox, safari
Smartphone (please complete the following information):

Device: redmi K20 pro
OS: android
Browser: chrome

**Additional context**
I would love to work on it.

**Comment by atapas** [comment]
Assigned to you!

I am not able to reproduce it, though!

**Comment by harshsinghatz** [comment]
@muzaffar640 Are you still working on it?

**Comment by muzaffar640** [comment]
> @muzaffar640 Are you still working on it?

Yes @harshsinghatz , going to issue a PR in a while. I got caught up with other issues.

**Comment by harshsinghatz** [comment]
Great! was just checking

**Comment by atapas** [comment]
Its done

**Comment by TRIPLE-ADE** [comment]
is this still available

**Comment by masif2002** [comment]
@atapas This issue has been fixed right?

**Comment by ArslanYM** [comment]
@masif2002 Yes the issue still exists , 
![yes](https://user-images.githubusercontent.com/104521101/230571294-55bcf815-5935-490e-9861-4fdf4f0c70ca.png)


If you want to start working on it I will assign you.

**Comment by masif2002** [comment]
> If you want to start working on it I will assign you.
Cool, i'll be happy to work on this

**Comment by masif2002** [comment]
@atapas I have raised a PR (#1102) for this issue, can you please review it?
